# Generated by Django 4.1 on 2022-08-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteTaker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='id',
        ),
        migrations.AddField(
            model_name='notes',
            name='noteID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='userID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
